const la = { _id: '9114894',
  imdb_id: '9114894',
  tvdb_id: '354813',
  title: 'Stitched',
  year: '2018',
  slug: 'stitched',
  synopsis:
   'Four top-notch designers compete over three skill-testing fashion challenges.',
  runtime: '60',
  country: 'ca',
  network: 'Slice',
  air_day: 'Sunday',
  air_time: '21:00',
  status: 'returning series',
  num_seasons: 1,
  last_updated: 1544471867946,
  episodes:
   [ { tvdb_id: 6885305,
       season: 1,
       episode: 2,
       title: 'No Sew, No Flow',
       overview:
        'Creating a garment in their personal style without the use of needle, thread or sewing machines; and creating a look based on an old school photo.',
       date_based: false,
       first_aired: 1537146000,
       watched: [Object],
       torrents: [Object] },
     { tvdb_id: 6885306,
       season: 1,
       episode: 3,
       title: 'Cocktails Anyone?',
       overview:
        'Creating a cocktail dress featuring neon fabrics; and creating a garment using camping materials.',
       date_based: false,
       first_aired: 1537750800,
       watched: [Object],
       torrents: [Object] },
     { tvdb_id: 6885307,
       season: 1,
       episode: 4,
       title: 'Red Hot Runway',
       overview:
        'The designers show off their personal aesthetic using only denim; and creating a garment using hardware store materials.',
       date_based: false,
       first_aired: 1538355600,
       watched: [Object],
       torrents: [Object] },
     { tvdb_id: 6885308,
       season: 1,
       episode: 5,
       title: 'Whiskey Tango Fashion',
       overview:
        'The designers show off their personal aesthetic using only camouflage prints. Next, they are challenged to create looks packing style and innovation using only moving supplies. Ultimately, the designers must create a runway-worthy design inspired by rock \'n roll.',
       date_based: false,
       first_aired: 1538960400,
       watched: [Object],
       torrents: [Object] },
     { tvdb_id: 6885309,
       season: 1,
       episode: 6,
       title: 'Ice Cold Couture',
       overview:
        'In their signature challenge, the designers must apply their design aesthetic to a garment that features fringe. For their surprise challenge, they will create a garment for style influencer Valeria Lipovetsky that is inspired by a Marshall\'s trend.',
       date_based: false,
       first_aired: 1539565200,
       watched: [Object],
       torrents: [Object] },
     { tvdb_id: 6885310,
       season: 1,
       episode: 7,
       title: 'Paper, Jock, Stitches',
       overview:
        'In their Signature Challenge, the designers show off their style inspired by athleisure. For their Surprise Challenge, they must try not to fold as they create garments using only different types of paper.',
       date_based: false,
       first_aired: 1540170000,
       watched: [Object],
       torrents: [Object] },
     { tvdb_id: 6885311,
       season: 1,
       episode: 8,
       title: 'On the Good Ship Fashion',
       overview:
        'The designers show off their unique design style in a nautical look. Also includes creating slam dunk garments using only sporting goods.',
       date_based: false,
       first_aired: 1540774800,
       watched: [Object],
       torrents: [Object] },
     { tvdb_id: 6893058,
       season: 1,
       episode: 9,
       title: 'Flights of Fashion',
       overview:
        'The designers must apply their personal design style to a piece of men\'s outerwear. Also includes creating a fashionable and thrifty look from yard sale materials.',
       date_based: false,
       first_aired: 1541383200,
       watched: [Object],
       torrents: [Object] },
     { tvdb_id: 6893067,
       season: 1,
       episode: 10,
       title: 'Planet Fashion',
       overview:
        'In their Signature Challenge, the designers must create a garment in their unique style using floral fabrics. For their Surprise Challenge, they will create a garment using materials found in a piece of "lost luggage" from a vacation.',
       date_based: false,
       first_aired: 1541988000,
       watched: [Object],
       torrents: [Object] } ],
  genres: [ 'reality' ],
  images:
   { poster: 'http://thetvdb.com/banners/posters/5bdff0d1b44a4.jpg',
     fanart:
      'http://thetvdb.com/banners/fanart/original/5bdfe5b15312f.jpg',
     banner: 'images/posterholder.png' },
  latest_episode: 1541988000,
  rating:
   { percentage: 0, watching: 0, votes: 0, loved: 100, hated: 100 },
  __v: 0 };
